[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
mbank_csv = { path = "../portfolio_loader/mbank_csv" }
domain = { path = "../domain" }
profit = { path = "../profit" }
risk = { path = "../risk" }
